### ISSUE TITLE
Application does not fill the screen on large displays (Motorola Xoom)

### ISSUE THREAD

**Issue by kamikazeduck** [paulmach/Text-Edit-for-Android#2]
The application does not fill the screen on a stock Motorola Xoom tablet.  It only displays in a screen size akin to a phone, though otherwise it seems to work perfectly.  The Motorola Xoom is a 10.1 inch tablet running Android Honeycomb 3.0.

**Comment by ghost** [comment]
I'm working on a project which is using Paul Mach's Text Edit code. 

Does this problem you describe happen with any other applications you have installed? 

Are there any open source projects you've installed which do not have this problem?

Frank Westlake

**Comment by kamikazeduck** [comment]
On Sun, Mar 13, 2011 at 8:59 AM, FrankWestlake <
reply@reply.github.com>wrote:

> I'm working on a project which is using Paul Mach's Text Edit code.
> 
> Does this problem you describe happen with any other applications you have
> installed?
> 
> Are there any open source projects you've installed which do not have this
> problem?
> 
> Frank Westlake
> 
> https://github.com/paulmach/Text-Edit-for-Android/issues/2#comment_865951

Yes, some other programs do that, but not many.  The vast majority work just
fine and fill the screen completely.  Just not this one.

I'm not sure which apps I've installed are OS and which aren't.  I imagine
most aren't.  Sorry I can't be more specific.

**Comment by ghost** [comment]
I think I've found the solution. Please test MachEdit.screentest.apk from here:

  https://github.com/FrankWestlake/Mach-Edit/downloads

If it works I'll e-mail the changes to Paul Mach.

Frank Westlake

**Comment by kamikazeduck** [comment]
It works!  All my tests seem to work perfectly.  However there is a new bug:
the file browser just doesn't work at all.  When I try to use it, it just
displays a black empty box and I can't do anything with it.

Also, I found an article by Google on enabling hardware acceleration in
Honeycomb.  I know a simple text editor hardly needs it but hey... more
speed is always welcome, right?  Here it is:

http://android-developers.blogspot.com/2011/03/android-30-hardware-acceleration.html

And though this may be a bit if a step beyond what you'd originally
intended, but there are other various Honeycomb enhancements that might have
a place in the app such as Fragments and/or adjusting the menu structure to
coincide more with Honeycomb's preferred layout.  Just a thought.
On Mar 20, 2011 8:49 AM, "FrankWestlake" <
reply@reply.github.com>
wrote:

**Comment by ghost** [comment]
Thank you for testing that. The reference is:
  http://developer.android.com/guide/practices/screens_support.html

I added this to the manifest:
        <supports-screens
            android:anyDensity="true"
            android:normalScreens="true"
            android:smallScreens="true"
            android:largeScreens="true"
            android:resizeable="true">
        </supports-screens>

And I created these additional project directories:

  res/drawable-hdpi
  res/drawable-nodpi

I think that to support extra large screens I would have to increase the minimum SDK version and I don't know if that is desirable.

Regarding the blank file browser dialog, I might have fixed that. When I inserted the lines above into the manifest I placed them in the package area, above the application area. It seems to me that should cover everything. I have now moved them down into the application area where they apparently belong. If you wish to try this new version it is the file "MachEdit.screentest2.apk" at:

  https://github.com/FrankWestlake/Mach-Edit/downloads

Thank you.

Frank Westlake

**Comment by ghost** [comment]
Thank you for testing that. The reference is:
  http://developer.android.com/guide/practices/screens_support.html

I added this to the manifest:
        <supports-screens
            android:anyDensity="true"
            android:normalScreens="true"
            android:smallScreens="true"
            android:largeScreens="true"
            android:resizeable="true">
        </supports-screens>

And I created these additional project directories:

  res/drawable-hdpi
  res/drawable-nodpi

I think that to support extra large screens I would have to increase the minimum SDK version and I don't know if that is desirable.

Regarding the blank file browser dialog, I might have fixed that. When I inserted the lines above into the manifest I placed them in the package area, above the application area. It seems to me that should cover everything. I have now moved them down into the application area where they apparently belong. If you wish to try this new version it is the file "MachEdit.screentest2.apk" at:

  https://github.com/FrankWestlake/Mach-Edit/downloads

Thank you.

Frank Westlake

**Comment by kamikazeduck** [comment]
On Mon, Mar 21, 2011 at 7:35 AM, FrankWestlake <
reply@reply.github.com>wrote:

> Thank you for testing that. The reference is:
>  http://developer.android.com/guide/practices/screens_support.html
> 
> I added this to the manifest:
>                <supports-screens
>                        android:anyDensity="true"
>                        android:normalScreens="true"
>                        android:smallScreens="true"
>                        android:largeScreens="true"
>                        android:resizeable="true">
>                </supports-screens>
> 
> And I created these additional project directories:
> 
>  res/drawable-hdpi
>  res/drawable-nodpi
> 
> I think that to support extra large screens I would have to increase the
> minimum SDK version and I don't know if that is desirable.
> 
> Regarding the blank file browser dialog, I might have fixed that. When I
> inserted the lines above into the manifest I placed them in the package
> area, above the application area. It seems to me that should cover
> everything. I have now moved them down into the application area where they
> apparently belong. If you wish to try this new version it is the file
> "MachEdit.screentest2.apk" at:
> 
>  https://github.com/FrankWestlake/Mach-Edit/downloads

Sadly no.  Still doesn't work; same result as before.  Everything else seems
to still work, however.

**Comment by ghost** [comment]
I think it's going to require someone with more Android experience than I have. Perhaps Paul will figure it out when he gets time.

I don't yet understand how Android selects resources but I think the problem might be the two icons on the file browser dialog. A wild guess is that the empty resource directories is telling Android to use no resource for this screen size. This seems unlikely but I have no other guesses. If you wish to try this change it is screen test 3 at:

  https://github.com/FrankWestlake/Mach-Edit/downloads

Frank

**Comment by kamikazeduck** [comment]
On Mon, Mar 21, 2011 at 9:29 AM, FrankWestlake <
reply@reply.github.com>wrote:

> I think it's going to require someone with more Android experience than I
> have. Perhaps Paul will figure it out when he gets time.
> 
> I don't yet understand how Android selects resources but I think the
> problem might be the two icons on the file browser dialog. A wild guess is
> that the empty resource directories is telling Android to use no resource
> for this screen size. This seems unlikely but I have no other guesses. If
> you wish to try this change it is screen test 3 at:
> 
>  https://github.com/FrankWestlake/Mach-Edit/downloads

Nope.  Same result.

**Comment by kamikazeduck** [comment]
On Mon, Mar 21, 2011 at 12:08 PM, Kamikaze Duck kamikaze.duck@gmail.comwrote:

> On Mon, Mar 21, 2011 at 9:29 AM, FrankWestlake <
> reply@reply.github.com>wrote:
> 
> > I think it's going to require someone with more Android experience than I
> > have. Perhaps Paul will figure it out when he gets time.
> > 
> > I don't yet understand how Android selects resources but I think the
> > problem might be the two icons on the file browser dialog. A wild guess is
> > that the empty resource directories is telling Android to use no resource
> > for this screen size. This seems unlikely but I have no other guesses. If
> > you wish to try this change it is screen test 3 at:
> > 
> >  https://github.com/FrankWestlake/Mach-Edit/downloads
> 
> Nope.  Same result.

Actually there's a new bug that I didn't notice before (it may be in
previous versions as well).  When I try to save anything, it says Access
Denied and I can't save!  This happens for both new documents and existing
ones.

**Comment by ghost** [comment]
Kamikaze Duck wrote:
^ When I try to save anything, it says Access
^ Denied and I can't save!

File saving is handled in a dialog so these two problems are both related to dialogs. I'll have a little time to look at it Wednesday (PDT) and more time Thursday.

Frank

**Comment by ghost** [comment]
I still haven't found any information useful in solving this problem. I changed two values in the manifest for experimentation, if you are still willing to test. I changed android:anyDensity and android:resizeable to false. This test ls named "MachEdit.2011.03.24.apk — Testing screen" at:

  https://github.com/FrankWestlake/Mach-Edit/downloads

If this fails I'll disable largescreen so that users with large screens will have dialogs again.

I've noticed that Paul Mach's e-mail address has been changed to the result of a mad attack on the keyboard so I hope I haven't upset him by handling this here. Perhaps any further work on this should be done in MachEdit's issue interface.

Frank

Frank

**Comment by kamikazeduck** [comment]
Same result.
On Mar 26, 2011 2:07 PM, "FrankWestlake" <
reply@reply.github.com>
wrote:

**Comment by paulmach** [comment]
I think this is fixed with v1.4.1

**Comment by kamikazeduck** [comment]
On Sep 3, 2011 9:59 AM, "paulmach" <
reply@reply.github.com>
wrote:

> I think this is fixed with v1.4.1

Nope.  Still broken.

**Comment by paulmach** [comment]
I don't have a xoom, but I can tell you that I emailed with another user who said it was fixed and I tried the emulator and it worked there.

At this point there is nothing more I can do about this.

**Comment by kamikazeduck** [comment]
Just to be clear, I'm not referring to the issue where the program doesn't
fill the screen, I'm referring to the Open dialogue box showing as a black
box with nothing clickable in it.

**Comment by paulmach** [comment]
okay....  next time please create a new issue for that.

I can't reproduce it so it will be hard for me to do anything about it. Sorry.
